#!/bin/sh
enable=1
start()
{
[ -z "$DOCUMENT_ROOT" ] && export DOCUMENT_ROOT=`main.sbin where_DOCUMENT_ROOT`
if
[ -x /usr/local/shadowsocks-libev/bin/ss-redir ]
then
main.sbin notice option="add" \
				read="0" \
				desc="_NOTICE_Shadowsocks_libev_binary_need_install" \
				detail="_NOTICE_Shadowsocks_libev_binary_need_install" \
				uniqid="Shadowsocks_libev_binary_need_install" \
				time="" \
				ergen="red" \
				dest="shadowsocks-libev" \
				dest_type="app" >/dev/null 2>&1
fi
mkdir -p /var/run/shadowsocks && chown shadowsocks /var/run/shadowsocks
if
[ $enable -eq 1 ]
then
ps aux | grep -q "ss-redir -c /usr/local/shadowsocks-libev/etc/redir.json -a shadowsocks " | grep -v grep || /usr/local/shadowsocks-libev/bin/ss-redir -c /usr/local/shadowsocks-libev/etc/redir.json -a shadowsocks -u -f /var/run/shadowsocks/shadowsocks-redir.pid
else
killall ss-redir || pkill ss-redir
fi
exit
}
stop()
{
killall ss-redir || pkill ss-redir
}
[ -z "$1" ] && start || $1