#!/bin/sh

main()
{
cat <<'EOF'
<script type="text/javascript">
$(function(){
  $('#save').on('submit', function(e){
    e.preventDefault();
    var data = "app=resolv-conf-edit&"+$(this).serialize();
    var url = 'index.cgi';
    Ha.common.ajax(url, 'json', data, 'post', 'ajax-fluid');
  });
});
</script>
EOF
cat <<EOF
<div class="col-md-6">
<legend>$_LANG_Current_resolv_conf_file_contents</legend>
<form id="save">
<textarea style="width:100%;height:260px" name="resolv_conf_str" class="bg-warning">
`cat /etc/resolv.conf`
</textarea>
<input type="hidden" name="action" value="save">
<button class="btn btn-primary" id="_submit" type="submit">$_LANG_Save</button>
</form>
</div>
<div class="col-md-6">
<legend>$_LANG_Attention</legend>
<pre>
# Generated by NetworkManager
nameserver 114.114.114.114

</pre>
<p>$_LANG_Please_carefully_modified<p>
</div>
EOF
}
save()
{
if
echo "$FORM_resolv_conf_str" | grep -q "nameserver "
then
echo "$FORM_resolv_conf_str" > /etc/resolv.conf

main.sbin notice option="add" \
				read="0" \
				desc="_NOTICE_do_resolv_conf_file_edit" \
				detail="_NOTICE_do_resolv_conf_file_edit" \
				uniqid="" \
				time="" \
				ergen="red" \
				dest="resolv-conf-edit" \
				dest_type="app"  >/dev/null 2>&1


(echo "$_LANG_Save_success" | main.sbin output_json 0) || exit 0
else
(echo "$_LANG_Need nameserver" | main.sbin output_json 1) || exit 1
fi
}

lang=`main.sbin get_client_lang`
eval `cat $DOCUMENT_ROOT/apps/$FORM_app/i18n/$lang/i18n.conf`

if
[ $is_main_page = 1 ]
then
main
elif [ -n "$FORM_action" ]
then
$FORM_action
fi